name: Lint and Format

on: [push, pull_request]

jobs:
  lint-and-format:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        pip install pylint flake8 black mypy

    - name: Run Flake8
      run: flake8 **/*.py

    - name: Run Black (Check)
      run: black --check **/*.py

    - name: Run Mypy
      run: mypy **/*.py
